services:
  postgres:
    image: postgres:17-alpine
    container_name: pm-profile-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: profile_user
      POSTGRES_PASSWORD: profile_password
      POSTGRES_DB: profile_db

    ports:
      - "5432:5432"

    volumes:
      - profile_postgres_data:/var/lib/postgresql/data

volumes:
  profile_postgres_data: